import { useEffect, useMemo, useRef, useState } from "react";
import { noteDocx, noteHtml } from "./note-export";
import { invoke } from "@tauri-apps/api/core";
import { open, save } from "@tauri-apps/plugin-dialog";
import MarkdownMessage from "./MarkdownMessage";

type Note = { id: string; title: string; body: string; createdAt: number; updatedAt: number };
type ConvertedDocument = { markdown: string; sourceName: string; sourceKind: string };
const empty = { title: "", body: "" };
const safeError = (error: unknown, fallback: string) => typeof error === "string" && error.length < 240 ? error : fallback;

export default function KnowledgeWorkspace() {
  const [notes,setNotes]=useState<Note[]>([]); const [selectedId,setSelectedId]=useState(""); const [draft,setDraft]=useState(empty); const [root,setRoot]=useState(""); const [query,setQuery]=useState(""); const [notice,setNotice]=useState(""); const [preview,setPreview]=useState(true); const [removeArmed,setRemoveArmed]=useState(false); const editor=useRef<HTMLTextAreaElement>(null);
  const selected=notes.find((item)=>item.id===selectedId); const filtered=useMemo(()=>notes.filter((item)=>`${item.title}\n${item.body}`.toLowerCase().includes(query.toLowerCase())),[notes,query]);
  async function refresh(preferred?:string){const values=await invoke<Note[]>("list_notes");setNotes(values);const id=preferred ?? (values.some(item=>item.id===selectedId)?selectedId:values[0]?.id||"");setSelectedId(id);const value=values.find((item)=>item.id===id);setDraft(value?{title:value.title,body:value.body}:empty);}
  useEffect(()=>{void refresh().catch(()=>setNotice("个人笔记仅在桌面应用中可用。"));invoke<string|null>("get_notes_root").then((value)=>setRoot(value||"")).catch(()=>undefined);},[]);
  function dirty(){return draft.title!==(selected?.title||"")||draft.body!==(selected?.body||"");}
  function canLeave(){if(!dirty())return true;setNotice("请先保存当前编辑，再切换或新建笔记。");return false;}
  function choose(id:string){if(id!==selectedId&&!canLeave())return;const value=notes.find((item)=>item.id===id);setSelectedId(id);setDraft(value?{title:value.title,body:value.body}:empty);setRemoveArmed(false);}
  function insert(before:string,after=""){setPreview(false);const area=editor.current;if(!area){setDraft({...draft,body:draft.body+before+after});return;}const start=area.selectionStart,end=area.selectionEnd;const body=draft.body.slice(0,start)+before+draft.body.slice(start,end)+after+draft.body.slice(end);setDraft({...draft,body});requestAnimationFrame(()=>{area.focus();area.setSelectionRange(start+before.length,end+before.length);});}
  async function selectRoot(){const path=await open({directory:true,multiple:false});if(typeof path!=="string")return;try{const mapped=await invoke<string>("set_notes_root",{path});setRoot(mapped);setNotice("笔记已映射到所选目录下的“芯智笔记”文件夹。");}catch(error){setNotice(safeError(error,"无法设置笔记目录。"));}}
  async function persist(){try{const saved=await invoke<Note>("save_note",{input:{id:selectedId||null,...draft}});await refresh(saved.id);setNotice(root?"笔记已保存并同步到本地映射目录。":"笔记已保存到本机数据库；可选择目录建立 Markdown 映射。");}catch(error){setNotice(safeError(error,"无法保存笔记。"));}}
  async function importDocument(){if(!canLeave())return;const path=await open({directory:false,multiple:false,filters:[{name:"笔记来源",extensions:["md","txt","docx","pdf"]}]});if(typeof path!=="string")return;try{const converted=await invoke<ConvertedDocument>("convert_document",{path});const saved=await invoke<Note>("save_note",{input:{id:null,title:converted.sourceName.replace(/\.(md|txt|docx|pdf)$/i,""),body:converted.markdown}});await refresh(saved.id);setNotice(`${converted.sourceKind} 已在本机转换并作为新笔记导入，请复核自动排版。`);}catch(error){setNotice(safeError(error,"文档导入失败。"));}}
  function addImage(file?:File){if(!file)return;if(!["image/png","image/jpeg","image/webp"].includes(file.type)||file.size>2*1024*1024){setNotice("笔记图片仅支持 PNG/JPEG/WebP，单张不超过 2 MiB。");return;}const reader=new FileReader();reader.onload=()=>insert(`\n![${file.name}](${String(reader.result)})\n`);reader.readAsDataURL(file);}
  async function exportAs(format:"md"|"pdf"|"doc"|"docx"){if(!draft.title.trim())return;const path=await save({defaultPath:`${draft.title.replace(/[\\/:*?"<>|]/g,"-")}.${format}`,filters:[{name:format.toUpperCase(),extensions:[format]}]});if(!path)return;try{const formatted = format==="docx" ? await noteDocx(draft.title,draft.body) : format==="doc" ? noteHtml(draft.title,draft.body) : null;await invoke("export_note",{path,format,title:draft.title,body:draft.body,formatted});setNotice(`已导出 ${format.toUpperCase()} 笔记。`);}catch(error){setNotice(safeError(error,"笔记导出失败。"));}}
  async function remove(){if(!selectedId)return;if(!removeArmed){setRemoveArmed(true);setNotice("再次点击确认删除本地笔记及其映射 Markdown 文件。");return;}try{await invoke("delete_note",{noteId:selectedId});setSelectedId("");setDraft(empty);await refresh("");setRemoveArmed(false);setNotice("笔记已删除。");}catch(error){setNotice(safeError(error,"无法删除笔记。"));}}
  return <section className="knowledge-workspace" aria-labelledby="knowledge-title"><header className="workspace-action-header"><div><p className="eyebrow">LOCAL KNOWLEDGE NOTEBOOK</p><h2 id="knowledge-title">个人知识笔记</h2><p>Markdown 作为本地可移植事实源；文档导入、图片和导出均在当前设备处理。</p></div><div><button className="secondary-button" onClick={selectRoot}>设置存储目录</button><button className="secondary-button" onClick={importDocument}>导入文档</button><button className="primary-button" onClick={()=>{if(!canLeave())return;setSelectedId("");setDraft(empty);setPreview(false);setRemoveArmed(false);}}>新建笔记</button></div></header>{notice?<p className="converter-notice" role="status">{notice}</p>:null}<div className="knowledge-root"><span>本地映射</span><code>{root||"尚未设置（当前保存于应用数据库）"}</code></div><div className="knowledge-layout"><aside className="notebook-rail"><strong>我的笔记本</strong><button className="active"><span>▤</span>全部笔记<small>{notes.length}</small></button><p>图文 · 表格 · 本地保存</p></aside><aside className="note-list"><input aria-label="搜索笔记" placeholder="搜索笔记…" value={query} onChange={(e)=>setQuery(e.target.value)}/>{filtered.map((note)=><button className={note.id===selectedId?"active":""} key={note.id} onClick={()=>choose(note.id)}><strong>{note.title}</strong><p>{note.body.replace(/[#*|>`!\[\]()]/g,"").slice(0,80)||"空白笔记"}</p><time>{new Date(note.updatedAt*1000).toLocaleString("zh-CN")}</time></button>)}</aside><main className="note-editor"><input className="note-title" aria-label="笔记标题" placeholder="无标题笔记" value={draft.title} onChange={(e)=>setDraft({...draft,title:e.target.value})}/><div className="note-toolbar"><button onClick={()=>insert("## ")}>标题</button><button onClick={()=>insert("**","**")}>粗体</button><button onClick={()=>insert("- ")}>列表</button><button onClick={()=>insert("- [ ] ")}>待办</button><button onClick={()=>insert("\n| 项目 | 内容 |\n|---|---|\n| 参数 | 数值 |\n")}>表格</button><label>图片<input type="file" accept="image/png,image/jpeg,image/webp" onChange={(e)=>addImage(e.target.files?.[0])}/></label><button className={preview?"active":""} onClick={()=>setPreview(!preview)}>{preview?"编辑":"预览"}</button></div>{preview?<div className="note-preview"><MarkdownMessage allowDataImages text={draft.body||"_开始输入，或导入 Markdown、Word、PDF 文档。_"}/></div>:<textarea ref={editor} aria-label="笔记内容" placeholder="支持 Markdown 文本、表格与图片…" value={draft.body} onChange={(e)=>setDraft({...draft,body:e.target.value})}/>}<footer><div><button onClick={()=>exportAs("md")}>Markdown</button><button onClick={()=>exportAs("pdf")}>PDF</button><button onClick={()=>exportAs("doc")}>DOC</button><button onClick={()=>exportAs("docx")}>DOCX</button></div><div>{selected?<button className="text-button danger" onClick={remove}>{removeArmed?"确认删除":"删除"}</button>:null}<button className="primary-button" disabled={!draft.title.trim()} onClick={persist}>保存笔记</button></div></footer></main></div></section>;
}
